// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/hubfuse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Share struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Alias          string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Permissions    string                 `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`                             // "ro" | "rw"
	AllowedDevices []string               `protobuf:"bytes,3,rep,name=allowed_devices,json=allowedDevices,proto3" json:"allowed_devices,omitempty"` // device_id or "all"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_proto_hubfuse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{0}
}

func (x *Share) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Share) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *Share) GetAllowedDevices() []string {
	if x != nil {
		return x.AllowedDevices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	SshPort       int32                  `protobuf:"varint,4,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	Shares        []*Share               `protobuf:"bytes,5,rep,name=shares,proto3" json:"shares,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_hubfuse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DeviceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DeviceInfo) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *DeviceInfo) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *JoinRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ClientCert    []byte                 `protobuf:"bytes,3,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	ClientKey     []byte                 `protobuf:"bytes,4,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,5,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JoinResponse) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *JoinResponse) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *JoinResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Shares          []*Share               `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	SshPort         int32                  `protobuf:"varint,2,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *RegisterRequest) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *RegisterRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DevicesOnline []*DeviceInfo          `protobuf:"bytes,3,rep,name=devices_online,json=devicesOnline,proto3" json:"devices_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetDevicesOnline() []*DeviceInfo {
	if x != nil {
		return x.DevicesOnline
	}
	return nil
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNickname   string                 `protobuf:"bytes,1,opt,name=new_nickname,json=newNickname,proto3" json:"new_nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{6}
}

func (x *RenameRequest) GetNewNickname() string {
	if x != nil {
		return x.NewNickname
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{7}
}

func (x *RenameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{8}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shares        []*Share               `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSharesRequest) Reset() {
	*x = UpdateSharesRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSharesRequest) ProtoMessage() {}

func (x *UpdateSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSharesRequest.ProtoReflect.Descriptor instead.
func (*UpdateSharesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSharesRequest) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

type UpdateSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSharesResponse) Reset() {
	*x = UpdateSharesResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSharesResponse) ProtoMessage() {}

func (x *UpdateSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSharesResponse.ProtoReflect.Descriptor instead.
func (*UpdateSharesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSharesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{12}
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{13}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{14}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_DeviceOnline
	//	*Event_DeviceOffline
	//	*Event_SharesUpdated
	//	*Event_PairingRequested
	//	*Event_PairingCompleted
	//	*Event_SubscribeReady
	//	*Event_DeviceRemoved
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_hubfuse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetDeviceOnline() *DeviceOnlineEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_DeviceOnline); ok {
			return x.DeviceOnline
		}
	}
	return nil
}

func (x *Event) GetDeviceOffline() *DeviceOfflineEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_DeviceOffline); ok {
			return x.DeviceOffline
		}
	}
	return nil
}

func (x *Event) GetSharesUpdated() *SharesUpdatedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_SharesUpdated); ok {
			return x.SharesUpdated
		}
	}
	return nil
}

func (x *Event) GetPairingRequested() *PairingRequestedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_PairingRequested); ok {
			return x.PairingRequested
		}
	}
	return nil
}

func (x *Event) GetPairingCompleted() *PairingCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_PairingCompleted); ok {
			return x.PairingCompleted
		}
	}
	return nil
}

func (x *Event) GetSubscribeReady() *SubscribeReadyEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_SubscribeReady); ok {
			return x.SubscribeReady
		}
	}
	return nil
}

func (x *Event) GetDeviceRemoved() *DeviceRemovedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_DeviceRemoved); ok {
			return x.DeviceRemoved
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_DeviceOnline struct {
	DeviceOnline *DeviceOnlineEvent `protobuf:"bytes,1,opt,name=device_online,json=deviceOnline,proto3,oneof"`
}

type Event_DeviceOffline struct {
	DeviceOffline *DeviceOfflineEvent `protobuf:"bytes,2,opt,name=device_offline,json=deviceOffline,proto3,oneof"`
}

type Event_SharesUpdated struct {
	SharesUpdated *SharesUpdatedEvent `protobuf:"bytes,3,opt,name=shares_updated,json=sharesUpdated,proto3,oneof"`
}

type Event_PairingRequested struct {
	PairingRequested *PairingRequestedEvent `protobuf:"bytes,4,opt,name=pairing_requested,json=pairingRequested,proto3,oneof"`
}

type Event_PairingCompleted struct {
	PairingCompleted *PairingCompletedEvent `protobuf:"bytes,5,opt,name=pairing_completed,json=pairingCompleted,proto3,oneof"`
}

type Event_SubscribeReady struct {
	SubscribeReady *SubscribeReadyEvent `protobuf:"bytes,6,opt,name=subscribe_ready,json=subscribeReady,proto3,oneof"`
}

type Event_DeviceRemoved struct {
	DeviceRemoved *DeviceRemovedEvent `protobuf:"bytes,7,opt,name=device_removed,json=deviceRemoved,proto3,oneof"`
}

func (*Event_DeviceOnline) isEvent_Payload() {}

func (*Event_DeviceOffline) isEvent_Payload() {}

func (*Event_SharesUpdated) isEvent_Payload() {}

func (*Event_PairingRequested) isEvent_Payload() {}

func (*Event_PairingCompleted) isEvent_Payload() {}

func (*Event_SubscribeReady) isEvent_Payload() {}

func (*Event_DeviceRemoved) isEvent_Payload() {}

type SubscribeReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeReadyEvent) Reset() {
	*x = SubscribeReadyEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReadyEvent) ProtoMessage() {}

func (x *SubscribeReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReadyEvent.ProtoReflect.Descriptor instead.
func (*SubscribeReadyEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{16}
}

type DeviceOnlineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	SshPort       int32                  `protobuf:"varint,4,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	Shares        []*Share               `protobuf:"bytes,5,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceOnlineEvent) Reset() {
	*x = DeviceOnlineEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceOnlineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceOnlineEvent) ProtoMessage() {}

func (x *DeviceOnlineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceOnlineEvent.ProtoReflect.Descriptor instead.
func (*DeviceOnlineEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{17}
}

func (x *DeviceOnlineEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceOnlineEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DeviceOnlineEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DeviceOnlineEvent) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *DeviceOnlineEvent) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

type DeviceOfflineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceOfflineEvent) Reset() {
	*x = DeviceOfflineEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceOfflineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceOfflineEvent) ProtoMessage() {}

func (x *DeviceOfflineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceOfflineEvent.ProtoReflect.Descriptor instead.
func (*DeviceOfflineEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceOfflineEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceOfflineEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type DeviceRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRemovedEvent) Reset() {
	*x = DeviceRemovedEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRemovedEvent) ProtoMessage() {}

func (x *DeviceRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRemovedEvent.ProtoReflect.Descriptor instead.
func (*DeviceRemovedEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{19}
}

func (x *DeviceRemovedEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRemovedEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SharesUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Shares        []*Share               `protobuf:"bytes,2,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharesUpdatedEvent) Reset() {
	*x = SharesUpdatedEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharesUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharesUpdatedEvent) ProtoMessage() {}

func (x *SharesUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharesUpdatedEvent.ProtoReflect.Descriptor instead.
func (*SharesUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{20}
}

func (x *SharesUpdatedEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SharesUpdatedEvent) GetShares() []*Share {
	if x != nil {
		return x.Shares
	}
	return nil
}

type PairingRequestedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDeviceId  string                 `protobuf:"bytes,1,opt,name=from_device_id,json=fromDeviceId,proto3" json:"from_device_id,omitempty"`
	FromNickname  string                 `protobuf:"bytes,2,opt,name=from_nickname,json=fromNickname,proto3" json:"from_nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequestedEvent) Reset() {
	*x = PairingRequestedEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequestedEvent) ProtoMessage() {}

func (x *PairingRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequestedEvent.ProtoReflect.Descriptor instead.
func (*PairingRequestedEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{21}
}

func (x *PairingRequestedEvent) GetFromDeviceId() string {
	if x != nil {
		return x.FromDeviceId
	}
	return ""
}

func (x *PairingRequestedEvent) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

type PairingCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerDeviceId  string                 `protobuf:"bytes,1,opt,name=peer_device_id,json=peerDeviceId,proto3" json:"peer_device_id,omitempty"`
	PeerPublicKey string                 `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingCompletedEvent) Reset() {
	*x = PairingCompletedEvent{}
	mi := &file_proto_hubfuse_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingCompletedEvent) ProtoMessage() {}

func (x *PairingCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingCompletedEvent.ProtoReflect.Descriptor instead.
func (*PairingCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{22}
}

func (x *PairingCompletedEvent) GetPeerDeviceId() string {
	if x != nil {
		return x.PeerDeviceId
	}
	return ""
}

func (x *PairingCompletedEvent) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

type RequestPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToDevice      string                 `protobuf:"bytes,1,opt,name=to_device,json=toDevice,proto3" json:"to_device,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairingRequest) Reset() {
	*x = RequestPairingRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairingRequest) ProtoMessage() {}

func (x *RequestPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairingRequest.ProtoReflect.Descriptor instead.
func (*RequestPairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{23}
}

func (x *RequestPairingRequest) GetToDevice() string {
	if x != nil {
		return x.ToDevice
	}
	return ""
}

func (x *RequestPairingRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type RequestPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairingResponse) Reset() {
	*x = RequestPairingResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairingResponse) ProtoMessage() {}

func (x *RequestPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairingResponse.ProtoReflect.Descriptor instead.
func (*RequestPairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{24}
}

func (x *RequestPairingResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type ConfirmPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,2,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPairingRequest) Reset() {
	*x = ConfirmPairingRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPairingRequest) ProtoMessage() {}

func (x *ConfirmPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPairingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{25}
}

func (x *ConfirmPairingRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *ConfirmPairingRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ConfirmPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PeerPublicKey string                 `protobuf:"bytes,3,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPairingResponse) Reset() {
	*x = ConfirmPairingResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPairingResponse) ProtoMessage() {}

func (x *ConfirmPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPairingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{26}
}

func (x *ConfirmPairingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPairingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfirmPairingResponse) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_hubfuse_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{27}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_hubfuse_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hubfuse_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hubfuse_proto_rawDescGZIP(), []int{28}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_proto_hubfuse_proto protoreflect.FileDescriptor

const file_proto_hubfuse_proto_rawDesc = "" +
	"\n" +
	"\x13proto/hubfuse.proto\x12\ahubfuse\"h\n" +
	"\x05Share\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12 \n" +
	"\vpermissions\x18\x02 \x01(\tR\vpermissions\x12'\n" +
	"\x0fallowed_devices\x18\x03 \x03(\tR\x0eallowedDevices\"\xb0\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x19\n" +
	"\bssh_port\x18\x04 \x01(\x05R\asshPort\x12&\n" +
	"\x06shares\x18\x05 \x03(\v2\x0e.hubfuse.ShareR\x06shares\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"F\n" +
	"\vJoinRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"\x97\x01\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vclient_cert\x18\x03 \x01(\fR\n" +
	"clientCert\x12\x1d\n" +
	"\n" +
	"client_key\x18\x04 \x01(\fR\tclientKey\x12\x17\n" +
	"\aca_cert\x18\x05 \x01(\fR\x06caCert\"\x7f\n" +
	"\x0fRegisterRequest\x12&\n" +
	"\x06shares\x18\x01 \x03(\v2\x0e.hubfuse.ShareR\x06shares\x12\x19\n" +
	"\bssh_port\x18\x02 \x01(\x05R\asshPort\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x05R\x0fprotocolVersion\"~\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\x0edevices_online\x18\x03 \x03(\v2\x13.hubfuse.DeviceInfoR\rdevicesOnline\"2\n" +
	"\rRenameRequest\x12!\n" +
	"\fnew_nickname\x18\x01 \x01(\tR\vnewNickname\"@\n" +
	"\x0eRenameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10HeartbeatRequest\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x13UpdateSharesRequest\x12&\n" +
	"\x06shares\x18\x01 \x03(\v2\x0e.hubfuse.ShareR\x06shares\"0\n" +
	"\x14UpdateSharesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11DeregisterRequest\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x10SubscribeRequestJ\x04\b\x01\x10\x02R\tdevice_id\"\x8e\x04\n" +
	"\x05Event\x12A\n" +
	"\rdevice_online\x18\x01 \x01(\v2\x1a.hubfuse.DeviceOnlineEventH\x00R\fdeviceOnline\x12D\n" +
	"\x0edevice_offline\x18\x02 \x01(\v2\x1b.hubfuse.DeviceOfflineEventH\x00R\rdeviceOffline\x12D\n" +
	"\x0eshares_updated\x18\x03 \x01(\v2\x1b.hubfuse.SharesUpdatedEventH\x00R\rsharesUpdated\x12M\n" +
	"\x11pairing_requested\x18\x04 \x01(\v2\x1e.hubfuse.PairingRequestedEventH\x00R\x10pairingRequested\x12M\n" +
	"\x11pairing_completed\x18\x05 \x01(\v2\x1e.hubfuse.PairingCompletedEventH\x00R\x10pairingCompleted\x12G\n" +
	"\x0fsubscribe_ready\x18\x06 \x01(\v2\x1c.hubfuse.SubscribeReadyEventH\x00R\x0esubscribeReady\x12D\n" +
	"\x0edevice_removed\x18\a \x01(\v2\x1b.hubfuse.DeviceRemovedEventH\x00R\rdeviceRemovedB\t\n" +
	"\apayload\"\x15\n" +
	"\x13SubscribeReadyEvent\"\x9f\x01\n" +
	"\x11DeviceOnlineEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x19\n" +
	"\bssh_port\x18\x04 \x01(\x05R\asshPort\x12&\n" +
	"\x06shares\x18\x05 \x03(\v2\x0e.hubfuse.ShareR\x06shares\"M\n" +
	"\x12DeviceOfflineEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"M\n" +
	"\x12DeviceRemovedEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"Y\n" +
	"\x12SharesUpdatedEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12&\n" +
	"\x06shares\x18\x02 \x03(\v2\x0e.hubfuse.ShareR\x06shares\"b\n" +
	"\x15PairingRequestedEvent\x12$\n" +
	"\x0efrom_device_id\x18\x01 \x01(\tR\ffromDeviceId\x12#\n" +
	"\rfrom_nickname\x18\x02 \x01(\tR\ffromNickname\"e\n" +
	"\x15PairingCompletedEvent\x12$\n" +
	"\x0epeer_device_id\x18\x01 \x01(\tR\fpeerDeviceId\x12&\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\tR\rpeerPublicKey\"S\n" +
	"\x15RequestPairingRequest\x12\x1b\n" +
	"\tto_device\x18\x01 \x01(\tR\btoDevice\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"9\n" +
	"\x16RequestPairingResponse\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"h\n" +
	"\x15ConfirmPairingRequest\x12\x1f\n" +
	"\vinvite_code\x18\x02 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKeyJ\x04\b\x01\x10\x02R\tdevice_id\"p\n" +
	"\x16ConfirmPairingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x0fpeer_public_key\x18\x03 \x01(\tR\rpeerPublicKey\"\x14\n" +
	"\x12ListDevicesRequest\"D\n" +
	"\x13ListDevicesResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.hubfuse.DeviceInfoR\adevices2\xbc\x05\n" +
	"\aHubFuse\x123\n" +
	"\x04Join\x12\x14.hubfuse.JoinRequest\x1a\x15.hubfuse.JoinResponse\x12?\n" +
	"\bRegister\x12\x18.hubfuse.RegisterRequest\x1a\x19.hubfuse.RegisterResponse\x129\n" +
	"\x06Rename\x12\x16.hubfuse.RenameRequest\x1a\x17.hubfuse.RenameResponse\x12B\n" +
	"\tHeartbeat\x12\x19.hubfuse.HeartbeatRequest\x1a\x1a.hubfuse.HeartbeatResponse\x12K\n" +
	"\fUpdateShares\x12\x1c.hubfuse.UpdateSharesRequest\x1a\x1d.hubfuse.UpdateSharesResponse\x12E\n" +
	"\n" +
	"Deregister\x12\x1a.hubfuse.DeregisterRequest\x1a\x1b.hubfuse.DeregisterResponse\x128\n" +
	"\tSubscribe\x12\x19.hubfuse.SubscribeRequest\x1a\x0e.hubfuse.Event0\x01\x12Q\n" +
	"\x0eRequestPairing\x12\x1e.hubfuse.RequestPairingRequest\x1a\x1f.hubfuse.RequestPairingResponse\x12Q\n" +
	"\x0eConfirmPairing\x12\x1e.hubfuse.ConfirmPairingRequest\x1a\x1f.hubfuse.ConfirmPairingResponse\x12H\n" +
	"\vListDevices\x12\x1b.hubfuse.ListDevicesRequest\x1a\x1c.hubfuse.ListDevicesResponseB Z\x1egithub.com/ykhdr/hubfuse/protob\x06proto3"

var (
	file_proto_hubfuse_proto_rawDescOnce sync.Once
	file_proto_hubfuse_proto_rawDescData []byte
)

func file_proto_hubfuse_proto_rawDescGZIP() []byte {
	file_proto_hubfuse_proto_rawDescOnce.Do(func() {
		file_proto_hubfuse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hubfuse_proto_rawDesc), len(file_proto_hubfuse_proto_rawDesc)))
	})
	return file_proto_hubfuse_proto_rawDescData
}

var file_proto_hubfuse_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_hubfuse_proto_goTypes = []any{
	(*Share)(nil),                  // 0: hubfuse.Share
	(*DeviceInfo)(nil),             // 1: hubfuse.DeviceInfo
	(*JoinRequest)(nil),            // 2: hubfuse.JoinRequest
	(*JoinResponse)(nil),           // 3: hubfuse.JoinResponse
	(*RegisterRequest)(nil),        // 4: hubfuse.RegisterRequest
	(*RegisterResponse)(nil),       // 5: hubfuse.RegisterResponse
	(*RenameRequest)(nil),          // 6: hubfuse.RenameRequest
	(*RenameResponse)(nil),         // 7: hubfuse.RenameResponse
	(*HeartbeatRequest)(nil),       // 8: hubfuse.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 9: hubfuse.HeartbeatResponse
	(*UpdateSharesRequest)(nil),    // 10: hubfuse.UpdateSharesRequest
	(*UpdateSharesResponse)(nil),   // 11: hubfuse.UpdateSharesResponse
	(*DeregisterRequest)(nil),      // 12: hubfuse.DeregisterRequest
	(*DeregisterResponse)(nil),     // 13: hubfuse.DeregisterResponse
	(*SubscribeRequest)(nil),       // 14: hubfuse.SubscribeRequest
	(*Event)(nil),                  // 15: hubfuse.Event
	(*SubscribeReadyEvent)(nil),    // 16: hubfuse.SubscribeReadyEvent
	(*DeviceOnlineEvent)(nil),      // 17: hubfuse.DeviceOnlineEvent
	(*DeviceOfflineEvent)(nil),     // 18: hubfuse.DeviceOfflineEvent
	(*DeviceRemovedEvent)(nil),     // 19: hubfuse.DeviceRemovedEvent
	(*SharesUpdatedEvent)(nil),     // 20: hubfuse.SharesUpdatedEvent
	(*PairingRequestedEvent)(nil),  // 21: hubfuse.PairingRequestedEvent
	(*PairingCompletedEvent)(nil),  // 22: hubfuse.PairingCompletedEvent
	(*RequestPairingRequest)(nil),  // 23: hubfuse.RequestPairingRequest
	(*RequestPairingResponse)(nil), // 24: hubfuse.RequestPairingResponse
	(*ConfirmPairingRequest)(nil),  // 25: hubfuse.ConfirmPairingRequest
	(*ConfirmPairingResponse)(nil), // 26: hubfuse.ConfirmPairingResponse
	(*ListDevicesRequest)(nil),     // 27: hubfuse.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 28: hubfuse.ListDevicesResponse
}
var file_proto_hubfuse_proto_depIdxs = []int32{
	0,  // 0: hubfuse.DeviceInfo.shares:type_name -> hubfuse.Share
	0,  // 1: hubfuse.RegisterRequest.shares:type_name -> hubfuse.Share
	1,  // 2: hubfuse.RegisterResponse.devices_online:type_name -> hubfuse.DeviceInfo
	0,  // 3: hubfuse.UpdateSharesRequest.shares:type_name -> hubfuse.Share
	17, // 4: hubfuse.Event.device_online:type_name -> hubfuse.DeviceOnlineEvent
	18, // 5: hubfuse.Event.device_offline:type_name -> hubfuse.DeviceOfflineEvent
	20, // 6: hubfuse.Event.shares_updated:type_name -> hubfuse.SharesUpdatedEvent
	21, // 7: hubfuse.Event.pairing_requested:type_name -> hubfuse.PairingRequestedEvent
	22, // 8: hubfuse.Event.pairing_completed:type_name -> hubfuse.PairingCompletedEvent
	16, // 9: hubfuse.Event.subscribe_ready:type_name -> hubfuse.SubscribeReadyEvent
	19, // 10: hubfuse.Event.device_removed:type_name -> hubfuse.DeviceRemovedEvent
	0,  // 11: hubfuse.DeviceOnlineEvent.shares:type_name -> hubfuse.Share
	0,  // 12: hubfuse.SharesUpdatedEvent.shares:type_name -> hubfuse.Share
	1,  // 13: hubfuse.ListDevicesResponse.devices:type_name -> hubfuse.DeviceInfo
	2,  // 14: hubfuse.HubFuse.Join:input_type -> hubfuse.JoinRequest
	4,  // 15: hubfuse.HubFuse.Register:input_type -> hubfuse.RegisterRequest
	6,  // 16: hubfuse.HubFuse.Rename:input_type -> hubfuse.RenameRequest
	8,  // 17: hubfuse.HubFuse.Heartbeat:input_type -> hubfuse.HeartbeatRequest
	10, // 18: hubfuse.HubFuse.UpdateShares:input_type -> hubfuse.UpdateSharesRequest
	12, // 19: hubfuse.HubFuse.Deregister:input_type -> hubfuse.DeregisterRequest
	14, // 20: hubfuse.HubFuse.Subscribe:input_type -> hubfuse.SubscribeRequest
	23, // 21: hubfuse.HubFuse.RequestPairing:input_type -> hubfuse.RequestPairingRequest
	25, // 22: hubfuse.HubFuse.ConfirmPairing:input_type -> hubfuse.ConfirmPairingRequest
	27, // 23: hubfuse.HubFuse.ListDevices:input_type -> hubfuse.ListDevicesRequest
	3,  // 24: hubfuse.HubFuse.Join:output_type -> hubfuse.JoinResponse
	5,  // 25: hubfuse.HubFuse.Register:output_type -> hubfuse.RegisterResponse
	7,  // 26: hubfuse.HubFuse.Rename:output_type -> hubfuse.RenameResponse
	9,  // 27: hubfuse.HubFuse.Heartbeat:output_type -> hubfuse.HeartbeatResponse
	11, // 28: hubfuse.HubFuse.UpdateShares:output_type -> hubfuse.UpdateSharesResponse
	13, // 29: hubfuse.HubFuse.Deregister:output_type -> hubfuse.DeregisterResponse
	15, // 30: hubfuse.HubFuse.Subscribe:output_type -> hubfuse.Event
	24, // 31: hubfuse.HubFuse.RequestPairing:output_type -> hubfuse.RequestPairingResponse
	26, // 32: hubfuse.HubFuse.ConfirmPairing:output_type -> hubfuse.ConfirmPairingResponse
	28, // 33: hubfuse.HubFuse.ListDevices:output_type -> hubfuse.ListDevicesResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_hubfuse_proto_init() }
func file_proto_hubfuse_proto_init() {
	if File_proto_hubfuse_proto != nil {
		return
	}
	file_proto_hubfuse_proto_msgTypes[15].OneofWrappers = []any{
		(*Event_DeviceOnline)(nil),
		(*Event_DeviceOffline)(nil),
		(*Event_SharesUpdated)(nil),
		(*Event_PairingRequested)(nil),
		(*Event_PairingCompleted)(nil),
		(*Event_SubscribeReady)(nil),
		(*Event_DeviceRemoved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hubfuse_proto_rawDesc), len(file_proto_hubfuse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hubfuse_proto_goTypes,
		DependencyIndexes: file_proto_hubfuse_proto_depIdxs,
		MessageInfos:      file_proto_hubfuse_proto_msgTypes,
	}.Build()
	File_proto_hubfuse_proto = out.File
	file_proto_hubfuse_proto_goTypes = nil
	file_proto_hubfuse_proto_depIdxs = nil
}
