// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: proto/hubfuse.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubFuse_Join_FullMethodName           = "/hubfuse.HubFuse/Join"
	HubFuse_Register_FullMethodName       = "/hubfuse.HubFuse/Register"
	HubFuse_Rename_FullMethodName         = "/hubfuse.HubFuse/Rename"
	HubFuse_Heartbeat_FullMethodName      = "/hubfuse.HubFuse/Heartbeat"
	HubFuse_UpdateShares_FullMethodName   = "/hubfuse.HubFuse/UpdateShares"
	HubFuse_Deregister_FullMethodName     = "/hubfuse.HubFuse/Deregister"
	HubFuse_Subscribe_FullMethodName      = "/hubfuse.HubFuse/Subscribe"
	HubFuse_RequestPairing_FullMethodName = "/hubfuse.HubFuse/RequestPairing"
	HubFuse_ConfirmPairing_FullMethodName = "/hubfuse.HubFuse/ConfirmPairing"
	HubFuse_ListDevices_FullMethodName    = "/hubfuse.HubFuse/ListDevices"
)

// HubFuseClient is the client API for HubFuse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubFuseClient interface {
	// Unauthenticated — first-time device registration
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UpdateShares(ctx context.Context, in *UpdateSharesRequest, opts ...grpc.CallOption) (*UpdateSharesResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// Server-streaming: push events to the agent
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	RequestPairing(ctx context.Context, in *RequestPairingRequest, opts ...grpc.CallOption) (*RequestPairingResponse, error)
	ConfirmPairing(ctx context.Context, in *ConfirmPairingRequest, opts ...grpc.CallOption) (*ConfirmPairingResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
}

type hubFuseClient struct {
	cc grpc.ClientConnInterface
}

func NewHubFuseClient(cc grpc.ClientConnInterface) HubFuseClient {
	return &hubFuseClient{cc}
}

func (c *hubFuseClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, HubFuse_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, HubFuse_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, HubFuse_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, HubFuse_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) UpdateShares(ctx context.Context, in *UpdateSharesRequest, opts ...grpc.CallOption) (*UpdateSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSharesResponse)
	err := c.cc.Invoke(ctx, HubFuse_UpdateShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, HubFuse_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubFuse_ServiceDesc.Streams[0], HubFuse_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubFuse_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *hubFuseClient) RequestPairing(ctx context.Context, in *RequestPairingRequest, opts ...grpc.CallOption) (*RequestPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPairingResponse)
	err := c.cc.Invoke(ctx, HubFuse_RequestPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) ConfirmPairing(ctx context.Context, in *ConfirmPairingRequest, opts ...grpc.CallOption) (*ConfirmPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPairingResponse)
	err := c.cc.Invoke(ctx, HubFuse_ConfirmPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubFuseClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, HubFuse_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubFuseServer is the server API for HubFuse service.
// All implementations must embed UnimplementedHubFuseServer
// for forward compatibility.
type HubFuseServer interface {
	// Unauthenticated — first-time device registration
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateShares(context.Context, *UpdateSharesRequest) (*UpdateSharesResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// Server-streaming: push events to the agent
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	RequestPairing(context.Context, *RequestPairingRequest) (*RequestPairingResponse, error)
	ConfirmPairing(context.Context, *ConfirmPairingRequest) (*ConfirmPairingResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	mustEmbedUnimplementedHubFuseServer()
}

// UnimplementedHubFuseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubFuseServer struct{}

func (UnimplementedHubFuseServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedHubFuseServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHubFuseServer) Rename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedHubFuseServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHubFuseServer) UpdateShares(context.Context, *UpdateSharesRequest) (*UpdateSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShares not implemented")
}
func (UnimplementedHubFuseServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedHubFuseServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHubFuseServer) RequestPairing(context.Context, *RequestPairingRequest) (*RequestPairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPairing not implemented")
}
func (UnimplementedHubFuseServer) ConfirmPairing(context.Context, *ConfirmPairingRequest) (*ConfirmPairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPairing not implemented")
}
func (UnimplementedHubFuseServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedHubFuseServer) mustEmbedUnimplementedHubFuseServer() {}
func (UnimplementedHubFuseServer) testEmbeddedByValue()                 {}

// UnsafeHubFuseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubFuseServer will
// result in compilation errors.
type UnsafeHubFuseServer interface {
	mustEmbedUnimplementedHubFuseServer()
}

func RegisterHubFuseServer(s grpc.ServiceRegistrar, srv HubFuseServer) {
	// If the following call panics, it indicates UnimplementedHubFuseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubFuse_ServiceDesc, srv)
}

func _HubFuse_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_UpdateShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).UpdateShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_UpdateShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).UpdateShares(ctx, req.(*UpdateSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubFuseServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubFuse_SubscribeServer = grpc.ServerStreamingServer[Event]

func _HubFuse_RequestPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).RequestPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_RequestPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).RequestPairing(ctx, req.(*RequestPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_ConfirmPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).ConfirmPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_ConfirmPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).ConfirmPairing(ctx, req.(*ConfirmPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubFuse_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubFuseServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubFuse_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubFuseServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubFuse_ServiceDesc is the grpc.ServiceDesc for HubFuse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubFuse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubfuse.HubFuse",
	HandlerType: (*HubFuseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _HubFuse_Join_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _HubFuse_Register_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _HubFuse_Rename_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HubFuse_Heartbeat_Handler,
		},
		{
			MethodName: "UpdateShares",
			Handler:    _HubFuse_UpdateShares_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _HubFuse_Deregister_Handler,
		},
		{
			MethodName: "RequestPairing",
			Handler:    _HubFuse_RequestPairing_Handler,
		},
		{
			MethodName: "ConfirmPairing",
			Handler:    _HubFuse_ConfirmPairing_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _HubFuse_ListDevices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HubFuse_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hubfuse.proto",
}
